use std::{
    collections::BTreeMap,
    env, fs,
    path::{Path, PathBuf},
};

fn main() {
    println!("cargo:rerun-if-changed=theme.toml");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is not set"));
    let colors = load_theme(Path::new("theme.toml"));
    generate_rust_theme(&out_dir, &colors);

    linker_be_nice();
}

fn load_theme(path: &Path) -> BTreeMap<String, u32> {
    let source = fs::read_to_string(path).expect("Failed to read theme.toml");
    let mut in_colors = false;
    let mut colors = BTreeMap::new();

    for (line_number, raw_line) in source.lines().enumerate() {
        let line = raw_line.trim();

        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        if line.starts_with('[') {
            in_colors = line == "[colors]";
            continue;
        }

        if !in_colors {
            continue;
        }

        let (name, value) = line.split_once('=').unwrap_or_else(|| {
            panic!(
                "theme.toml:{}: expected `name = \"#RRGGBB\"`",
                line_number + 1
            )
        });

        let name = name.trim();
        let value = value.trim().trim_matches('"');

        if name.is_empty() {
            panic!(
                "theme.toml:{}: color name must not be empty",
                line_number + 1
            );
        }

        let rgb = parse_rgb(value).unwrap_or_else(|| {
            panic!(
                "theme.toml:{}: `{}` must be a #RRGGBB color",
                line_number + 1,
                value
            )
        });

        if colors.insert(name.to_owned(), rgb).is_some() {
            panic!("theme.toml:{}: duplicate color `{}`", line_number + 1, name);
        }
    }

    for required in [
        "dark-blue",
        "light-blue",
        "dark-gray",
        "light-gray",
        "white",
        "black",
    ] {
        if !colors.contains_key(required) {
            panic!("theme.toml: missing required color `{required}`");
        }
    }

    colors
}

fn parse_rgb(value: &str) -> Option<u32> {
    let hex = value.strip_prefix('#')?;
    if hex.len() != 6 || !hex.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return None;
    }

    u32::from_str_radix(hex, 16).ok()
}

fn rust_name(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() {
                ch.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect()
}

fn rgb565(rgb: u32) -> u16 {
    let red = ((rgb >> 16) & 0xff) as u16;
    let green = ((rgb >> 8) & 0xff) as u16;
    let blue = (rgb & 0xff) as u16;

    ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)
}

fn generate_rust_theme(out_dir: &Path, colors: &BTreeMap<String, u32>) {
    let mut generated = String::from("// @generated by build.rs from theme.toml. Do not edit.\n\n");

    for (name, &rgb) in colors {
        let ident = rust_name(name);
        generated.push_str(&format!(
            "pub const {ident}_RGB565: u16 = 0x{:04X};\n",
            rgb565(rgb)
        ));
    }

    fs::write(out_dir.join("theme_generated.rs"), generated)
        .expect("Failed to write generated Rust theme");
}

fn linker_be_nice() {
    let args: Vec<String> = std::env::args().collect();
    if let Some(kind) = args.get(1) {
        let Some(what) = args.get(2) else {
            std::process::exit(1);
        };

        match kind.as_str() {
            "undefined-symbol" => match what.as_str() {
                what if what.starts_with("_defmt_") => {
                    eprintln!();
                    eprintln!(
                        "💡 `defmt` not found - make sure `defmt.x` is added as a linker script and you have included `use defmt_rtt as _;`"
                    );
                    eprintln!();
                }
                "_stack_start" => {
                    eprintln!();
                    eprintln!("💡 Is the linker script `linkall.x` missing?");
                    eprintln!();
                }
                what if what.starts_with("esp_rtos_") => {
                    eprintln!();
                    eprintln!(
                        "💡 `esp-radio` has no scheduler enabled. Make sure you have initialized `esp-rtos` or provided an external scheduler."
                    );
                    eprintln!();
                }
                "embedded_test_linker_file_not_added_to_rustflags" => {
                    eprintln!();
                    eprintln!(
                        "💡 `embedded-test` not found - make sure `embedded-test.x` is added as a linker script for tests"
                    );
                    eprintln!();
                }
                "free"
                | "malloc"
                | "calloc"
                | "get_free_internal_heap_size"
                | "malloc_internal"
                | "realloc_internal"
                | "calloc_internal"
                | "free_internal" => {
                    eprintln!();
                    eprintln!(
                        "💡 Did you forget the `esp-alloc` dependency or didn't enable the `compat` feature on it?"
                    );
                    eprintln!();
                }
                _ => (),
            },
            _ => std::process::exit(1),
        }

        std::process::exit(0);
    }

    println!(
        "cargo:rustc-link-arg=-Wl,--error-handling-script={}",
        std::env::current_exe().unwrap().display()
    );
}
