import { ListView } from "std-widgets.slint";
import { Theme } from "generated-theme.slint";

export component LogView inherits Rectangle {
    in property <[string]> log-lines: [];

    background: Theme.white;
    clip: true;

    ListView {
        x: 3px;
        y: 3px;
        width: parent.width - 6px;
        height: parent.height - 6px;
        horizontal-scrollbar-policy: always-off;

        for line in root.log-lines : Rectangle {
            width: parent.width;
            height: 15px;
            background: Theme.white;

            Text {
                x: 2px;
                width: parent.width - 4px;
                height: parent.height;
                text: line;
                color: Theme.black;
                font-size: 9px;
                vertical-alignment: center;
            }
        }
    }
}
