export component NetworkIcon inherits Rectangle {
    in property <color> icon-color;

    Rectangle {
        x: 12px; y: 16px; width: 20px; height: 2px;
        background: root.icon-color;
    }
    Rectangle {
        x: 13px; y: 17px; width: 2px; height: 13px;
        background: root.icon-color;
    }
    Rectangle {
        x: 29px; y: 17px; width: 2px; height: 13px;
        background: root.icon-color;
    }
    Rectangle {
        x: 10px; y: 12px; width: 7px; height: 7px; border-radius: 4px;
        background: root.icon-color;
    }
    Rectangle {
        x: 27px; y: 12px; width: 7px; height: 7px; border-radius: 4px;
        background: root.icon-color;
    }
    Rectangle {
        x: 18px; y: 27px; width: 8px; height: 8px; border-radius: 4px;
        background: root.icon-color;
    }
    Rectangle {
        x: 14px; y: 29px; width: 16px; height: 2px;
        background: root.icon-color;
    }
}

export component AccelerometerIcon inherits Rectangle {
    in property <color> icon-color;

    Rectangle {
        x: 11px; y: 23px; width: 22px; height: 2px;
        background: root.icon-color;
    }
    Rectangle {
        x: 21px; y: 13px; width: 2px; height: 22px;
        background: root.icon-color;
    }
    Rectangle {
        x: 13px; y: 31px; width: 5px; height: 5px; border-radius: 3px;
        background: root.icon-color;
    }
    Rectangle {
        x: 29px; y: 12px; width: 5px; height: 5px; border-radius: 3px;
        background: root.icon-color;
    }
    Rectangle {
        x: 19px; y: 21px; width: 6px; height: 6px; border-radius: 3px;
        background: root.icon-color;
    }
}

export component MicrophoneIcon inherits Rectangle {
    in property <color> icon-color;

    Rectangle {
        x: 17px; y: 9px; width: 10px; height: 20px; border-radius: 5px;
        background: root.icon-color;
    }
    Rectangle {
        x: 13px; y: 23px; width: 2px; height: 7px;
        background: root.icon-color;
    }
    Rectangle {
        x: 29px; y: 23px; width: 2px; height: 7px;
        background: root.icon-color;
    }
    Rectangle {
        x: 14px; y: 29px; width: 16px; height: 2px;
        background: root.icon-color;
    }
    Rectangle {
        x: 21px; y: 30px; width: 2px; height: 6px;
        background: root.icon-color;
    }
    Rectangle {
        x: 17px; y: 35px; width: 10px; height: 2px;
        background: root.icon-color;
    }
}

export component SpeakerIcon inherits Rectangle {
    in property <color> icon-color;

    Rectangle {
        x: 10px; y: 20px; width: 7px; height: 9px;
        background: root.icon-color;
    }
    Rectangle {
        x: 17px; y: 16px; width: 5px; height: 17px;
        background: root.icon-color;
    }
    Rectangle {
        x: 27px; y: 21px; width: 2px; height: 7px;
        background: root.icon-color;
    }
    Rectangle {
        x: 32px; y: 17px; width: 2px; height: 15px;
        background: root.icon-color;
    }
}

export component LogIcon inherits Rectangle {
    in property <color> icon-color;

    Rectangle {
        x: 10px; y: 14px; width: 4px; height: 4px; border-radius: 2px;
        background: root.icon-color;
    }
    Rectangle {
        x: 17px; y: 15px; width: 17px; height: 2px;
        background: root.icon-color;
    }
    Rectangle {
        x: 10px; y: 22px; width: 4px; height: 4px; border-radius: 2px;
        background: root.icon-color;
    }
    Rectangle {
        x: 17px; y: 23px; width: 17px; height: 2px;
        background: root.icon-color;
    }
    Rectangle {
        x: 10px; y: 30px; width: 4px; height: 4px; border-radius: 2px;
        background: root.icon-color;
    }
    Rectangle {
        x: 17px; y: 31px; width: 17px; height: 2px;
        background: root.icon-color;
    }
}
