import { Theme } from "generated-theme.slint";

export component PlaceholderView inherits Rectangle {
    in property <string> title: "";
    in property <string> subtitle: "";

    background: Theme.white;

    VerticalLayout {
        padding: 14px;
        spacing: 8px;
        alignment: center;

        Text {
            text: root.title;
            color: Theme.black;
            font-size: 18px;
            horizontal-alignment: center;
        }

        Text {
            text: root.subtitle;
            color: Theme.dark-gray;
            font-size: 10px;
            horizontal-alignment: center;
        }
    }
}
