export component PlaceholderView inherits Rectangle {
    in property <string> title: "";
    in property <string> subtitle: "";

    background: #ffffff;

    VerticalLayout {
        padding: 14px;
        spacing: 8px;
        alignment: center;

        Text {
            text: root.title;
            color: #202020;
            font-size: 18px;
            horizontal-alignment: center;
        }

        Text {
            text: root.subtitle;
            color: #707070;
            font-size: 10px;
            horizontal-alignment: center;
        }
    }
}
