[build]
target = "xtensa-esp32s3-none-elf"

[target.xtensa-esp32s3-none-elf]
rustflags = [
    "-C",
    "link-arg=-Tlinkall.x",
    "-C",
    "link-arg=-Wl,--no-warn-rwx-segments",
]

[unstable]
build-std = ["core", "alloc"]

[alias]
dist = "espflash save-image --chip esp32s3 --release --merge firmware.bin"
